let a=10;
let b=20;
let c=a+b;
let d=a-b;
let e=a*b;
let f=b/a;
console.log("Addition of a and b is : " + c);
console.log("Subtraction of a and b is : " + d);
console.log("Multiplication of a and b is : " + e);
console.log("Division of a and b is : " + f);